Format selection2
Andrii-Nik/learn pull request #4
Opened 2020-04-14 15:16 UTC by Andrii-Nik

2 fix

2020-04-14 15:21 UTC, injektoxa requested changes
No need to create new PR I can edit previous one

2020-04-14 15:21 UTC, injektoxa commented on Zayavka na konferenc.html
> +
extra space

2020-04-14 15:21 UTC, injektoxa commented on Zayavka na konferenc.html
> +
extra space

2020-04-14 15:21 UTC, injektoxa commented on Zayavka na konferenc.html
> +
extra space

2020-04-14 15:21 UTC, injektoxa commented on Zayavka na konferenc.html
> +    <input type="checkbox" name="Проживание в отеле"><label>Проживание в отеле</label><br>
<label>Проживание в отеле</label> should be on a new line

2020-04-15 13:52 UTC, Andrii-Nik commented on Zayavka na konferenc.html
> +    <input type="checkbox" name="Проживание в отеле"><label>Проживание в отеле</label><br>
ок

2020-04-15 13:52 UTC, Andrii-Nik commented on Zayavka na konferenc.html
> +
ок

2020-04-15 13:52 UTC, Andrii-Nik commented on Zayavka na konferenc.html
> +
ок

2020-04-15 14:29 UTC, Andrii-Nik commented on Zayavka na konferenc.html
> +
ок
![image](https://user-images.githubusercontent.com/63597502/79345332-a5d0a800-7f39-11ea-843d-81d9af788827.png)

2020-04-16 08:30 UTC, injektoxa commented on Zayavka na konferenc.html
> +
It can be valid html, but it is better looking for developers who will interact with your code. If you want to split code blocks on different sections it should be meaningful blocks.

2020-04-16 10:01 UTC, injektoxa approved these changes

2020-04-16 10:08 UTC, merged